[general]
APP_PASSWORD = "Seo!"

[SUPABASE]
URL = "https://ugpmpinhkdndajjflnfz.supabase.co"
KEY = "sb_publishable_sOvTFpHdhiVwgW1SL14TDA_tRcQ7pTx"

[dify]
BASE_URL = "http://dify.jaroslawmuzyka.pl/v1"
API_USER = "webinvest"

# Klucze API do poszczeg√≥lnych workflow
API_KEY_RESEARCH = "app-K8RD2wwXiDEyP0hg9JC75Orx"
API_KEY_HEADERS = "app-uTtWP4VkPXWZZLXhjEHogeyZ"
API_KEY_RAG = "app-fSlOmMwdQYfe2XEQax7MbZgu" 
API_KEY_BRIEF = "app-oJkkGYPKnqeKxTfnaLs3kaSc"
API_KEY_WRITE = "app-XYMED2k9MliIjp8uTzy2jejC"
API_KEY_AUDIT = "app-vfWxkhrFJa1kZhSkRFbKs9n7"
